README: Instructions for running
Pi-Squared-Network/proof-checker-public pull request #1
Opened 2023-11-09 20:30 UTC by nishantjr

2023-11-10 01:47 UTC, nishantjr commented on README.md
> +This repository contains implementations of the matchign logic proof checker using various ZK implementations.
```suggestion
This repository contains implementations of the matchign logic proof checker using various ZK implementations.
Note that the code in this repository is experimental and exploratory.
```

2023-11-10 01:48 UTC, nishantjr commented on README.md
> +* Run the tests: `scarb cairo-test`
```suggestion
In the `cairo` directory:

* Build the checker: `scarb build`
* Build and run the checker: `scarb cairo-run`
* Run the tests: `scarb cairo-test`
```

2023-11-13 06:22 UTC, xc93 requested changes

2023-11-13 06:22 UTC, xc93 commented on README.md
> +# $\Pi^2$ Proof Checkers
Implementations of the Pi2 Proof Checker

2023-11-13 06:22 UTC, xc93 commented on README.md
> +This repository contains implementations of the matchign logic proof checker using various ZK implementations.
using various ZK implementations => in Cairo, Risc0, and zkLLVM.

2023-11-13 06:22 UTC, xc93 commented on README.md
> +This repository contains implementations of the matchign logic proof checker using various ZK implementations.
Reorder the subsections accordingly (in alphabetical order).

2023-11-15 13:47 UTC, xc93 approved these changes

2023-11-15 13:48 UTC, merged