Performance.md review
Pi-Squared-Network/proof-checker-public pull request #8
Opened 2024-02-22 21:40 UTC by reekamaharaj

I have finished initial edits to `Performance.md`. Please review them when you get a chance. 

What I did: I cleaned up some of the language and then changed some formatting around the tables to make them collapsible. Right now they are all defaulted to `open` but they can be changed to default closed if we ever wanted that.

Immediate feedback needed: The section under **Performance Tables** has two options for how that can look. We can keep the bullet points or I can change them to the paragraphs. I think the paragraphs are better because the bullet points are a little confusing, it's a mixture of information and not one clear idea.

Just a thought: The last comment I have would be that we could group the information better. If we split the sections up into "Lurk", "RISC", and "zkLLVM" that makes more sense to me. It would also mean the tables are spread out through the file more. I didn't make any of these edits. If we decide this will be part of the content for the website then I think we should discuss this more.

2024-02-23 07:13 UTC, xc93 requested changes
I like these edits very much! Great work! Some minor comments can be found in my review. 

We can group the page by the ZK backend (Cairo, Lurk, ...), and for each such subsection (of a given ZK backend) we list the numbers for Direct Implementation, Proof of Proof, and Implementation Details. That sounds good to me. We can implement that change in next PR.

2024-02-23 07:13 UTC, xc93 commented on Performance.md
> +The pseudocode for these examples is provided at the end of this document.
Let's delete this sentence as the code is not at the end of the doc.

2024-02-23 07:13 UTC, xc93 commented on Performance.md
> +- Last Update: Dec 19th, 2023
There are many parts in this benchmark set and they have different "Last Update" dates. Either we change the date here to be the latest update date, or we simply remove it from here.

2024-02-23 07:13 UTC, xc93 commented on Performance.md
> +This section was last updated Dec 19th, 2023.
I do like the paragraph-version more. Let's use it.

2024-02-23 16:44 UTC, reekamaharaj commented
@xc93 I have updated it to remove the sentence about the pseudocode, changed the section on performance to the paragraph version, and removed the "last updated" dates.

I will get started on rearranging everything to be grouped by ZKbackends. We can get this merged in and I will submit another PR for the restructuring, that will take me a little more time to make sure it makes sense.

2024-02-24 00:04 UTC, xc93 approved these changes
LGTM.

2024-02-24 00:50 UTC, merged